[package]
name = "keylogger"
version = "0.0.1"
authors = ["Gulshan Singh <gsingh2011@gmail.com>"]

[dependencies]
getopts = "0.2.18"
libc = "0.2.48"
env_logger = "0.6.0"
log = "0.4.6"
chrono = "0.4.6"
